name: dart_slack

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/dart_slack.yaml"
      - "bin/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/dart_slack.yaml"
      - "bin/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v7

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.10.0"

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 🧹 Check Formatting
        run: dart format --set-exit-if-changed .

      - name: 🔎 Analyze
        run: dart analyze

      - name: 🧪 Run Tests
        run: dart test

  verify-version:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v7

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.10.0"

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 🔎 Verify version
        run: dart run test --run-skipped -t version-verify
